version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  build:
    docker:
      - image: cimg/android:2023.02
    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew lint test
workflows:
  example-workflow:
    jobs:
      - build